# Generated by Django 6.0.1 on 2026-02-27 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 27, 14, 37, 4, 465793, tzinfo=datetime.timezone.utc)),
        ),
    ]
