# Generated by Django 6.0.1 on 2026-02-27 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0002_alter_products_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 27, 15, 7, 54, 692172, tzinfo=datetime.timezone.utc)),
        ),
    ]
