# Generated by Django 6.0 on 2026-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0003_deliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_images/'),
        ),
    ]
