# Generated by Django 6.0.1 on 2026-02-27 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0004_alter_products_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 27, 15, 26, 20, 856363, tzinfo=datetime.timezone.utc)),
        ),
    ]
