# Generated by Django 6.0.1 on 2026-02-28 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0009_alter_products_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 28, 10, 58, 17, 391122, tzinfo=datetime.timezone.utc)),
        ),
    ]
