# Generated by Django 6.0.1 on 2026-03-04 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0017_alter_products_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 4, 17, 3, 38, 548849, tzinfo=datetime.timezone.utc)),
        ),
    ]
