# Generated by Django 6.0.1 on 2026-03-06 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0020_alter_products_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 6, 1, 21, 39, 113110, tzinfo=datetime.timezone.utc)),
        ),
    ]
