# Generated by Django 6.0.1 on 2026-03-07 03:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0021_alter_products_harvest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 7, 3, 11, 10, 236857, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='farmer',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_app.location'),
        ),
    ]
