# Generated by Django 6.0.1 on 2026-03-07 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0022_location_alter_products_harvest_date_farmer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_app.location'),
        ),
        migrations.AlterField(
            model_name='products',
            name='harvest_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
