# Generated by Django 6.0.1 on 2026-03-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0024_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
