# Generated by Django 6.0.1 on 2026-03-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0025_alter_farmer_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='last_name',
        ),
    ]
