# Generated by Django 6.0.1 on 2026-03-16 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0026_remove_farmer_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='liked_products',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.AddField(
            model_name='farmer',
            name='license',
            field=models.ImageField(default=1, upload_to='licenses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('name', models.CharField(max_length=50)),
                ('liked_products', models.ManyToManyField(blank=True, related_name='liked_by', to='farmer_app.products')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='farmer',
            name='buyer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer_app.buyer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='farmer_app.buyer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('buyer', 'product')},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='farmer',
        ),
    ]
