# Generated by Django 6.0.1 on 2026-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0027_remove_farmer_avatar_remove_farmer_liked_products_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('buyer', 'product'), name='unique_feedback'),
        ),
    ]
