# Generated by Django 6.0.1 on 2026-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0028_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
