# Generated by Django 6.0.1 on 2026-03-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0029_alter_farmer_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=255)),
                ('carnumber', models.CharField(max_length=10)),
                ('vehicle_registration', models.ImageField(upload_to='vehicle_registrations/')),
                ('insurance', models.ImageField(upload_to='insurancies/')),
                ('medical_certificate', models.ImageField(upload_to='insurancies/')),
            ],
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='fullname',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='buyer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer_app.buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='working_stage',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Professional')]),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_app.location'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='vehicle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer_app.cardetails'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.buyer')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmer_app.deliveries')),
            ],
        ),
    ]
