# Generated by Django 6.0.1 on 2026-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0030_cardetails_remove_deliveries_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='fullname',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='brand',
            field=models.CharField(default=11),
            preserve_default=False,
        ),
    ]
