# Generated by Django 6.0.1 on 2026-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0031_deliveries_fullname_farmer_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
