# Generated by Django 6.0.1 on 2026-03-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0032_alter_deliveries_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField()),
                ('result', models.CharField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.buyer')),
            ],
        ),
    ]
