# Generated by Django 6.0.1 on 2026-03-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0033_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.buyer'),
        ),
    ]
